### ISSUE TITLE
Missing top-level functions and variables

### ISSUE THREAD

**Issue by sethladd** [google/dart-shapeshift#4]
From a user:

Does it look at coverage for top-level functions and variables? When I run it on path, I just see the classes it contains.

**Comment by srawlins** [comment]
Good catch. I've just added top-level functions in a recent commit; will launch when I get variables in there too.

**Comment by sethladd** [comment]
Thanks!

**Comment by srawlins** [comment]
Done and done. Fixed both.

**Comment by sethladd** [comment]
Awesome, thank you! (is it deployed?)

**Comment by srawlins** [comment]
Yes sir, deployed.

**Comment by sethladd** [comment]
woohoo!
